services:
    oniti.docga.comparator.docga_type:
        class: Oniti\Docga\ConnectorBundle\Comparator\Attribute\DocgaComparator
        tags:
            - { name: pim_catalog.attribute.comparator }
