pim_oniti_docga_connector:
    settings:
        base_url:
            value: ~
            scope: app
        api_key:
            value: ~
            scope: app
        api_secret:
            value: ~
            scope: app
