services:
    oniti.docga.datagrid.filter.product_value.oniti_catalog_docga:
          class: Oniti\Docga\ConnectorBundle\DataGrid\Filter\ProductValue\DocgaBooleanFilter
          arguments:
              - '@form.factory'
              - '@pim_filter.product_utility'
          tags:
              - { name: oro_filter.extension.orm_filter.filter, type: product_value_docga }
